### ISSUE TITLE
support for passphrase in Trezor 1.0

### ISSUE THREAD

**Issue by fccoelho** [kayagoban/shadowlands#3]
Hi I tried connecting my Trezor 1.0 but I encoutered an error because I have a passphrase configured on my Trezor besides the numeric code. It seems that Shadowlands don't expect this and crashes with an AttributeError.

**Comment by kayagoban** [comment]
Ah, yes, it would - there’s no support for that feature yet on the Trezor.  It can only handle the PIN so far.

**Comment by kayagoban** [comment]
I'll add a line to the README.md to warn people about that.  Unknown when I'll be getting to this, but we'll leave the issue open.

**Comment by fccoelho** [comment]
Good Idea. It's actually easy to turn off passphrase security on the trezor
wallet.
That way trezor users can have a nice first experience with shadowlands.

Em sex, 12 de out de 2018 10:42, Chuck Thomas <notifications@github.com>
escreveu:

**Comment by carver** [comment]
This ended up being a dealbreaker for me to try it out. :-/

My Trezor is stuck on the screen "Please enter your passphrase..." and a stacktrace with `AttributeError: address` is smashed across the asciimatics screen.

**Comment by kayagoban** [comment]
Sigh. It’s painful to me, how the Trezor requires the user interface to take part in authentication.   The passphrase feature is particularly puzzling to me - if I trust that nobody is keylogging me, then why do I need a credstick?

I think I probably will have to implement this for the upcoming alpha release.

**Comment by kayagoban** [comment]
Fixed in the shadowlands-core repo by https://github.com/kayagoban/shadowlands-core/commit/b3dbcda11132471ac48a76052c22dc3677de4961

The alpha release of shadowlands will include this fix.
