### ISSUE TITLE
Acknowledging with Enter

### ISSUE THREAD

**Issue by carver** [kayagoban/shadowlands#7]
My fingers keep expecting [Enter] to work to submit a dialog. That would be nice IMO.

**Comment by kayagoban** [comment]
Strong agree.  Has always been in the back of my mind.  Hitting tab with no particular need is a crap user experience.

C Thomas
Soykaf Digital Systems LLC
ph. +14798568793
cthomas@soykaf.digital

**Comment by kayagoban** [comment]
Listbox provides this, changed a few dialogs to do this where appropriate.
