### ISSUE TITLE
Live demo video is broken

### ISSUE THREAD

**Issue by ChihChengLiang** [kayagoban/shadowlands#9]
It says 

> This recording has been archived
All unclaimed recordings (the ones not linked to any user account) are automatically archived 7 days after upload.

https://asciinema.org/a/zZeRkHwWUYk7QDOlSBdziUjeR

**Comment by kayagoban** [comment]
Thanks for letting me know.  I’ll record a new one.

C Thomas
Soykaf Digital Systems LLC
cthomas@soykaf.digital

**Comment by virgil** [comment]
@kayagoban are you looking for collaboration?  We're working on a new IDE and it be nice to work with shadowlands UI.

**Comment by kayagoban** [comment]
> @kayagoban are you looking for collaboration? We're working on a new IDE and it be nice to work with shadowlands UI.

Hi Virgil,

Would you email me?  I'd be interested to hear what you're in to.

cthomas@soykaf.digital

**Comment by kayagoban** [comment]
Posted new asciinema demo.
